version: "3.8"
services:
  db_test:
    container_name: "db_test"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    networks:
      - custom

  mongodb:
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=notification
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - custom

volumes:
  dbdata6:

networks:
  custom:
    driver: bridge
